var Lvs;Lvs==void 0&&(Lvs={});
Lvs.IncrementalSearch={init:function(a){var a=Object.extend(this.Configure,a),b=this.CacheData.getInstance();a.USE_HIDDEN_ITEM?this.buildForHidden(a,b):this.build(a,b)},build:function(a,b){var c=new this.TextInput($(a.TEXT_FIELD_ID),b,a);c.setSelect(new (a.ADDRESS_MODE?this.AddressSelectBox:this.SelectBox)(c,a))},buildForHidden:function(a,b){var c=new this.HiddenInput($(a.HIDDEN_FIELD_ID)),d=new this.TextInputWithHiddenInput($(a.TEXT_FIELD_ID),b,a,c);d.setSelect(new this.SelectBoxWithHiddenInput(d,a));
c=new this.Preprocessor(d,c,a);a.PREPROCESS_CALLBACK&&a.PREPROCESS_CALLBACK(c)}};
Lvs.IncrementalSearch.CacheData=Class.create({cache:null,keys:null,maxCacheSize:100,initialize:function(a){this.init();this.maxCacheSize=a||this.maxCacheSize},init:function(){this.cache=$H();this.keys=$H()},set:function(a,b){this.collectGarbage();this.keys.set(a,this.keys.get(a)?this.keys.get(a)+1:1);this.cache.set(a,b)},get:function(a){this.keys.set(a,this.keys.get(a)?this.keys.get(a)+1:1);return this.cache.get(a)},collectGarbage:function(){this.cache.size()<=this.maxCacheSize||(this.keys.filter(function(a){return a.value<=
1}).each(function(a){this.cache.unset(a.key);this.keys.unset(a.key)}.bind(this)),this.cache.size()>this.maxCacheSize/2&&this.keys.sortBy(function(a){return a.value}).select(function(a,b){return b<this.maxCacheSize/3}.bind(this)).each(function(a){this.cache.unset(a.key);this.keys.unset(a.key)}.bind(this)))}});Lvs.IncrementalSearch.CacheData.getInstance=function(a){if(this.instance==null)this.instance=new this(a);return this.instance};
Lvs.IncrementalSearch.Configure={USE_HIDDEN_ITEM:!1,ADDRESS_MODE:!1,REQUEST_URL:"/api/suggest_station",FULL_MATCH_URL:"/api/full_match_station",REQUEST_KEY:"query",TEXT_FIELD_ID:"incTextInput",HIDDEN_FIELD_ID:"incHiddenInput",SELECT_BOX_WIDTH:100,SELECT_BOX_LEFT_OFFSET:0,FOCUS_CALLBACK:function(){},Z_INDEX:2E3,PREPROCESS_CALLBACK:function(){}};
Lvs.IncrementalSearch.HiddenInput=Class.create({elem:null,initialize:function(a){this.elem=a},setValue:function(a){this.elem.value=a},getValue:function(){return this.elem.value},clear:function(){this.setValue("")}});
Lvs.IncrementalSearch.Preprocessor=Class.create({input:null,hidden:null,config:null,initialize:function(a,b,c){this.input=a;this.hidden=b;this.config=c},getText:function(){return this.input.getText()},setText:function(a){this.input.setText(a)},getId:function(){return this.hidden.getValue()},setId:function(a){this.hidden.setValue(a)},checkAndUpdate:function(a){if(a){var b=this.config.REQUEST_KEY,c=this.input.getText();new Ajax.Request(this.config.FULL_MATCH_URL,{method:"get",asynchronous:!1,parameters:b+
"="+c,onSuccess:a.curry(this)})}}});
Lvs.IncrementalSearch.SelectBox=Class.create({input:null,config:null,elem:null,list:null,options:null,selectedIndex:null,template:'<div class="incSelectList" style="width:#{width}px;"></div>',initialize:function(a,b){this.input=a;this.config=b;this.elem=this.createElement();this.list=this.elem.firstDescendant();this.options=[]},update:function(a){a.size()==0?this.hide():this.show(a)},hide:function(){this.clear();this.elem.hide()},isShow:function(){return this.options.size()>0},getInput:function(){return this.input},
moveDown:function(){this.selectedIndex==null?this.selectedIndex=0:this.selectedIndex<this.options.size()-1?this.selectedIndex++:this.selectedIndex=null;this.updateSelectedOption()},moveUp:function(){this.selectedIndex==null?this.selectedIndex=this.options.size()-1:this.selectedIndex>0?this.selectedIndex--:this.selectedIndex=null;this.updateSelectedOption()},selectByOption:function(a){this.options.each(function(b,c){a==b?(b.selected(),this.selectedIndex=c):b.unselected()}.bind(this))},createOption:function(a){return new Lvs.IncrementalSearch.SelectOption(this,
a.id,a.name)},setPosition:function(){this.elem.setStyle(this.input.getStyleUnderLeftPosition())},show:function(a){this.clear();this.addOptions(a);this.setPosition();this.elem.show();if(this.config.Z_INDEX)this.elem.style.zIndex=this.config.Z_INDEX},addOptions:function(a){this.options=$A(a).map(function(a){return this.createOption(a)}.bind(this))},clear:function(){this.options.each(function(a){a.remove()});this.options.clear();this.selectedIndex=null},createElement:function(){var a=new Element("div",
{className:"incSelectBox",style:"position: absolute;"});a.update((new Template(this.template)).evaluate({width:this.config.SELECT_BOX_WIDTH}));return $(a)},appendChild:function(a){this.list.appendChild(a)},removeChild:function(a){this.list.removeChild(a)},updateSelectedOption:function(){this.options.each(function(a){a.unselected()});if(this.selectedIndex!=null){var a=this.options[this.selectedIndex];a&&(a.selected(),this.input.setValue(a.getValue()))}}});
Lvs.IncrementalSearch.SelectBoxWithHiddenInput=Class.create(Lvs.IncrementalSearch.SelectBox,{initialize:function($super,b,c){$super(b,c);document.body.appendChild(this.elem)},createOption:function(a){return new Lvs.IncrementalSearch.SelectOptionWithHiddenInput(this,a.name,a.id)}});Lvs.IncrementalSearch.AddressSelectBox=Class.create(Lvs.IncrementalSearch.SelectBox,{createOption:function(a){return new Lvs.IncrementalSearch.AddressSelectOption(this,a)},setPosition:function(){},createElement:function(){return $("suggestBox")}});
Lvs==void 0&&(Lvs={});if(Lvs.Util==void 0)Lvs.Util={};Lvs.Util.Browser={isIE6:function(){return!this.isNotIE6()},isNotIE6:function(){return!Prototype.Browser.IE||Prototype.Browser.IE&&typeof document.documentElement.style.maxHeight!="undefined"}};
Lvs.IncrementalSearch.SelectOption=Class.create({select:null,name:null,elem:null,template:"#{text}",initialize:function(a,b){this.select=a;this.name=b;this.elem=this.createElement();this.select.appendChild(this.elem);this.setEventListener()},getValue:function(){return{text:this.name}},selected:function(){if(Lvs.Util.Browser.isIE6())this.elem.style.height="19px";this.elem.addClassName("selected")},unselected:function(){if(Lvs.Util.Browser.isIE6())this.elem.style.height="19px";this.elem.removeClassName("selected")},
remove:function(){this.select.removeChild(this.elem)},createElement:function(){var a=new Element("div");a.update((new Template(this.template)).evaluate({text:this.name}));return $(a)},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this));this.elem.observe("mouseover",this.mouseover.bindAsEventListener(this))},click:function(){this.select.getInput().setValue(this.getValue())},mouseover:function(){this.select.selectByOption(this)}});
Lvs.IncrementalSearch.SelectOptionWithHiddenInput=Class.create(Lvs.IncrementalSearch.SelectOption,{id:null,template:'#{text}<input type="hidden" value="#{id}" />',initialize:function($super,b,c,d){this.id=d;$super(b,c)},getValue:function(){return{text:this.name,id:this.id}}});
Lvs.IncrementalSearch.AddressSelectOption=Class.create(Lvs.IncrementalSearch.SelectOption,{template:'<li><a href="javascript:void(0);">#{text}</a></li>',selected:function(){this.elem.addClassName("selected")},unselected:function(){this.elem.removeClassName("selected")},createElement:function(){var a=this.select.getInput().getText(),b=new Element("ul");b.update((new Template(this.template)).evaluate({text:this.name.replace(a,"<b>"+a+"</b>")}));return $(b).down()}});
Lvs.IncrementalSearch.TextInput=Class.create({elem:null,select:null,cache:null,config:null,timerId:null,current:"",initialize:function(a,b,c){this.elem=a;this.cache=b;this.config=c;this.elem.setAttribute("autocomplete","off");this.setEventListener()},setSelect:function(a){this.select=a},setValue:function(a){this.setText(a.text)},getText:function(){return this.elem.value},setText:function(a){this.elem.value=a},getStyleUnderLeftPosition:function(){var a=this.elem.cumulativeOffset();return{top:a.top+
this.elem.getHeight()+"px",left:a.left+this.config.SELECT_BOX_LEFT_OFFSET+"px"}},reset:function(){},setEventListener:function(){Event.observe(this.elem,Prototype.Browser.Opera?"keypress":"keydown",this.keydown.bindAsEventListener(this));Event.observe(this.elem,"keyup",this.keyup.bindAsEventListener(this));Event.observe(this.elem,"blur",this.blur.bindAsEventListener(this));Event.observe(this.elem,"focus",this.config.FOCUS_CALLBACK);Event.observe(document.body,"click",this.clearAutocomplete.bindAsEventListener(this))},
keydown:function(a){switch(a.keyCode){case Event.KEY_ESC:case Event.KEY_TAB:case Event.KEY_RETURN:this.clearAutocomplete();break;case Event.KEY_DOWN:this.select.isShow()||this.change();this.select.moveDown();break;case Event.KEY_UP:this.select.isShow()?this.select.moveUp():(this.change(),this.select.moveDown());break;case Event.KEY_BACKSPACE:break;default:if(Prototype.Browser.Gecko&&this.timerId==null)this.timerId=setInterval(this.change.bind(this),100)}},keyup:function(a){this.clearDelayFunction();
switch(a.keyCode){case Event.KEY_DOWN:break;case Event.KEY_UP:break;case Event.KEY_BACKSPACE:this.change();break;default:Prototype.Browser.Gecko||this.change()}this.elem.value==""&&this.select.hide()},blur:function(){this.clearDelayFunction()},clearAutocomplete:function(){this.clearDelayFunction();this.select.hide()},clearDelayFunction:function(){if(this.timerId!=null)clearInterval(this.timerId),this.timerId=null},change:function(){var a=this.elem.value,b=this.current;this.current=a;a===""?this.clearAutocomplete():
(b!=a&&this.reset(),this.update(a))},update:function(a){var b=this.cache.get(a);b?this.select.update(b):this.searchAndUpdate(a)},searchAndUpdate:function(a){new Ajax.Request(this.config.REQUEST_URL,{method:"get",asynchronous:!0,parameters:this.config.REQUEST_KEY+"="+a,onSuccess:this.onSuccess.curry(a).bind(this)})},onSuccess:function(a,b){var c=b.responseJSON;this.cache.set(a,c);this.select.update(c)}});
Lvs.IncrementalSearch.TextInputWithHiddenInput=Class.create(Lvs.IncrementalSearch.TextInput,{hidden:null,initialize:function($super,b,c,d,e){$super(b,c,d);this.hidden=e},setValue:function(a){this.setText(a.text);this.setId(a.id)},reset:function(){this.setId("")},setId:function(a){this.hidden.setValue(a)}});