var Lvs;void 0==Lvs&&(Lvs={});void 0==Lvs.Search&&(Lvs.Search={});
Lvs.Search.Form={setup:function(a){a&&(Lvs.Search.Form.ModalWindow.setup(a),Lvs.Search.Form.JobCategoryButtonManager.setup($$(".li_job input"),$(document.getElementsByName("medical")[0])),Lvs.Search.Form.Counter.setup(a),Lvs.Search.Form.AreaChangeRadioButton.setup($A(document.getElementsByName("selectArea"))),Lvs.Search.Form.StationCheckbox.setup($$(".checkedStation input")),Lvs.Search.Form.StationCheckboxInLineTab.setup($$(".stationSliderCheckbox")),Lvs.Search.Form.TimeCheck.setup($$(Lvs.Search.Form.Configure.TIME_CSS_EXPR)),
Lvs.Search.Form.Tooltip.setup($$(".hintBtnToolTip")),Lvs.Search.Form.MoreSearchOptionButton.setup($("moreSearchOptionBtn"),$("moreSearchOption")),Lvs.Search.Form.NewMemberButton.setup($$(".newMessageBtn a, p.txtLink a"),a),Lvs.Search.Form.MoreGuideLinksToggle.setup($$("div.detailBtnArea a.guide_links_toggle"),$("hidden_guide_link")),Lvs.Search.Form.GuideLinks.setup($("search_panel_guide_link_parent"),$$("#search_panel_guide_link_list ul.itemList li input[type=checkbox]")))}};
Lvs.Search.Form.AreaChangeRadioButton=Class.create({elem:null,initialize:function(a){this.elem=a;this.setEventListener()},change:function(){$("selectArea").value=this.elem.value;$("jobCheckTable").hide();$("stationCheckTable").hide();$A(document.getElementsByClassName("checkedArea")).each(function(a){a.remove()});$A(document.getElementsByClassName("checkedStation")).each(function(a){a.remove()});$$(".jobStaSelect2").each(function(a){a.hide()});$("jobOrStaionCheckTable").show();$j(".jobStaSelect").fadeIn()},
setEventListener:function(){this.elem.observe("click",this.change.bindAsEventListener(this))}});Lvs.Search.Form.AreaChangeRadioButton.setup=function(a){$A(document.getElementsByName("selectArea")).each(function(a){new Lvs.Search.Form.AreaChangeRadioButton(a)})};
Lvs.Search.Form.Configure={SEARCH_FORM_ID:"searchForm",MODAL_WINDOW_ID:"modalWindow",AREA_OPEN_BUTTON_CLASS_NAME:"areaWindowOpenBtn",LINE_OPEN_BUTTON_CLASS_NAME:"lineWindowOpenBtn",TIME_OPEN_BUTTON_CLASS_NAME:"timeWindowOpenBtn",AREA_SELECT_AJAX_URL:"/modal_window/area",LINE_SELECT_AJAX_URL:"/modal_window/station",TIME_SELECT_AJAX_URL:"/modal_window/time",TIME_OPTION_AJAX_URL:"/modal_window/time/option",TAB_SELECTED_CLASS_NAME:"on",TIME_SELECTED_CLASS_NAME:"checkbox_checked",TAB_CSS_EXPR:".selectTabs ul li",
TIME_CSS_EXPR:".timeCheck li label",LINE_GET_AJAX_URL:"/modal_window/get_lines",STATION_GET_AJAX_URL:"/modal_window/get_stations",COUNT_URL:"/api/get_search_count",SET_CHOICE_URL:"/member/set_choice"};
Lvs.Search.Form.Counter=Class.create({elem:null,counter:null,initialize:function(a){this.elem=a;this.counter=$$("#matchNumber span");this.setEventListener()},update:function(a,b){var c=setInterval(this.setRandom.bind(this),30);new Ajax.Request(this.getUrl(),{method:"get",parameters:a.serialize(),asynchronous:!0,onSuccess:function(a){this.spotlightButton();clearInterval(c);this.setResponse(a.responseText)}.bind(this)})},setEventListener:function(){new Form.Observer(this.elem,.3,this.update.bind(this))},
getUrl:function(){return Lvs.Search.Form.Configure.COUNT_URL},setResponse:function(a){var b=(new String(("00000"+a).slice(-6))).toArray();this.counter.each(function(a,d){this.updateClassName(a,b[d])}.bind(this))},setRandom:function(){this.counter.each(function(a){this.updateClassName(a,Math.floor(10*Math.random()))}.bind(this))},updateClassName:function(a,b){a.className="num"+b},spotlightButton:function(){var a=$("searchButtonSpotlightArrow");a&&(a.show(),a.hide.bind(a).delay(2))}});
Lvs.Search.Form.Counter.setup=function(a){new Lvs.Search.Form.Counter(a)};
Lvs.Search.Form.GuideLinks=Class.create({parentLink:null,children:null,childrenCount:null,checkedCount:null,initialize:function(a,b){this.parentLink=a;this.children=b;this.childrenCount=b.size();this.checkedCount=this.getCheckedCount();this.setEventListener()},getCheckedCount:function(){return this.children.pluck("checked").findAll(function(a){return!!a}).size()},setEventListener:function(){this.children.each(function(a){a.observe("click",this.check.bindAsEventListener(this))}.bind(this))},check:function(a){a.element().checked?
++this.checkedCount:--this.checkedCount;0<this.checkedCount?this.parentLink.disable():this.parentLink.enable()}});Lvs.Search.Form.GuideLinks.setup=function(a,b){a&&b&&new Lvs.Search.Form.GuideLinks(a,b)};Lvs.Search.Form.MedicalCheckbox=Class.create({elem:null,job:null,initialize:function(a,b){this.elem=a;this.job=b;this.setEventListener()},change:function(){var a=$("hiddenExceptMedical");a&&(a.value=this.elem.checked?1:0);this.job.close()},setEventListener:function(){this.elem.observe("click",this.change.bindAsEventListener(this))}});
Lvs.Search.Form.JobCategoryButtonManager=Class.create({parent:null,children:null,initialize:function(a){this.parent=a;this.children=this.getChildren();this.setEventListener()},open:function(){this.parent.checked=!0;$j(this.children).slideDown("fast",function(){this.updateChildren(this.parent.checked)}.bind(this));if("medical"==this.parent.value){var a=document.getElementsByName("medical")[0];a&&a.checked&&(a.checked=!1)}},close:function(){this.parent.checked=!1;$j(this.children).slideUp("fast",function(){this.updateChildren(this.parent.checked)}.bind(this))},
getChildren:function(){return $("open_"+this.parent.id.match(/\d+/)[0])},setEventListener:function(){this.parent.observe("click",function(){this[this.parent.checked?"open":"close"]()}.bind(this))},updateChildren:function(a){this.children.getElementsBySelector("input").each(function(b){b.checked=a})}});Lvs.Search.Form.JobCategoryButtonManager.setup=function(a,b){a.each(function(a){var d=new Lvs.Search.Form.JobCategoryButtonManager(a);"medical"==a.value&&new Lvs.Search.Form.MedicalCheckbox(b,d)})};
Lvs.Search.Form.ModalWindow={setup:function(a){var b=new Lvs.Search.Form.ModalWindow.AreaFactory(a),c=new Lvs.Search.Form.ModalWindow.LineFactory(a),d=new Lvs.Search.Form.ModalWindow.TimeFactory(a);$A(document.getElementsByClassName(Lvs.Search.Form.Configure.AREA_OPEN_BUTTON_CLASS_NAME)).each(function(a){new Lvs.Search.Form.ModalWindow.OpenButton(a,b)});$A(document.getElementsByClassName(Lvs.Search.Form.Configure.LINE_OPEN_BUTTON_CLASS_NAME)).each(function(a){new Lvs.Search.Form.ModalWindow.OpenButton(a,
c)});$A(document.getElementsByClassName(Lvs.Search.Form.Configure.TIME_OPEN_BUTTON_CLASS_NAME)).each(function(a){new Lvs.Search.Form.ModalWindow.OpenButton(a,d)})}};
Lvs.Search.Form.ModalWindow.Base=Class.create({id:Lvs.Search.Form.Configure.MODAL_WINDOW_ID,elem:null,form:null,tabMgr:null,chkMgr:null,viewer:null,clearButtons:null,closeButtons:null,submitButtons:null,url:null,initialize:function(a,b){this.elem=a;this.form=b;this.tabMgr=this.createTabManager();this.chkMgr=this.createCheckboxManager()},getId:function(){return this.id},getCheckboxManager:function(){return this.chkMgr},getTabManager:function(){return this.tabMgr},getOverlay:function(){return $j("div."+
$j.fn.lightbox_me.defaults.classPrefix+"_overlay")[0]},clearAll:function(){this.chkMgr.clearCheckboxes();this.viewer.update()},getIgnoredUniqueInputsDecoratedWithLabel:function(){var a=this.chkMgr.getIgnoreChildren();return this.getUniqueInputsDecoratedWithLabel().filter(function(b){b=b.down();return!a.get(b.name.replace("[]","")+b.value)})},getUniqueInputsDecoratedWithLabel:function(){var a={};this.getInputsDecoratedWithLabel().each(function(b){var c=b.down();a[c.name+c.value]=b});return $H(a).values()},
getInputsDecoratedWithLabel:function(){return this.chkMgr.getInputsDecoratedWithLabel()},getAllParentByEachCheckedChildren:function(){return this.tabMgr.getAllParentByEachCheckedChildren()},getParentsIfAnyCheckedChildren:function(){return this.chkMgr.getParentsIfAnyCheckedChildren()},getCheckedSummaryText:function(){return this.chkMgr.getText()},getCurrentPrefId:function(){return this.tabMgr.getPrefId()},getChildrenCheckboxValues:function(){return this.chkMgr.getUniqueChildrenCheckedValues()},close:function(){this.getOverlay().removeModal(!0)},
setViewer:function(a){this.viewer=a},setClearButtons:function(a){this.clearButtons=a},setCloseButtons:function(a){this.closeButtons=a},setSubmitButtons:function(a){this.submitButtons=a},getUrl:function(){return this.url},createTabManager:function(){return new Lvs.Search.Form.ModalWindow.Tab.Manager},createCheckboxManager:function(){return new Lvs.Search.Form.ModalWindow.Checkbox.Manager},getTabContentsClass:function(){throw Error("Not Implementation Error");}});
Lvs.Search.Form.ModalWindow.Area=Class.create(Lvs.Search.Form.ModalWindow.Base,{url:Lvs.Search.Form.Configure.AREA_SELECT_AJAX_URL,getTabContentsClass:function(){return Lvs.Search.Form.ModalWindow.Tab.AreaContents}});Lvs.Search.Form.ModalWindow.Line=Class.create(Lvs.Search.Form.ModalWindow.Base,{url:Lvs.Search.Form.Configure.LINE_SELECT_AJAX_URL,getTabContentsClass:function(){return Lvs.Search.Form.ModalWindow.Tab.LineContents}});
Lvs.Search.Form.ModalWindow.Time=Class.create(Lvs.Search.Form.ModalWindow.Base,{url:Lvs.Search.Form.Configure.TIME_SELECT_AJAX_URL,getTabContentsClass:function(){return Lvs.Search.Form.ModalWindow.Tab.TimeContents},createCheckboxManager:function(){return new Lvs.Search.Form.ModalWindow.Checkbox.TimeManager}});void 0==Lvs&&(Lvs={});
Lvs.IncrementalSearch={init:function(a){a=Object.extend(this.Configure,a);var b=this.CacheData.getInstance();a.USE_HIDDEN_ITEM?this.buildForHidden(a,b):this.build(a,b)},build:function(a,b){var c=new this.TextInput($(a.TEXT_FIELD_ID),b,a);c.setSelect(new (a.ADDRESS_MODE?this.AddressSelectBox:this.SelectBox)(c,a))},buildForHidden:function(a,b){var c=new this.HiddenInput($(a.HIDDEN_FIELD_ID)),d=new this.TextInputWithHiddenInput($(a.TEXT_FIELD_ID),b,a,c);d.setSelect(new this.SelectBoxWithHiddenInput(d,
a));c=new this.Preprocessor(d,c,a);a.PREPROCESS_CALLBACK&&a.PREPROCESS_CALLBACK(c)}};
Lvs.IncrementalSearch.CacheData=Class.create({cache:null,keys:null,maxCacheSize:100,initialize:function(a){this.init();this.maxCacheSize=a||this.maxCacheSize},init:function(){this.cache=$H();this.keys=$H()},set:function(a,b){this.collectGarbage();this.keys.set(a,this.keys.get(a)?this.keys.get(a)+1:1);this.cache.set(a,b)},get:function(a){this.keys.set(a,this.keys.get(a)?this.keys.get(a)+1:1);return this.cache.get(a)},collectGarbage:function(){this.cache.size()<=this.maxCacheSize||(this.keys.filter(function(a){return 1>=
a.value}).each(function(a){this.cache.unset(a.key);this.keys.unset(a.key)}.bind(this)),this.cache.size()>this.maxCacheSize/2&&this.keys.sortBy(function(a){return a.value}).select(function(a,b){return b<this.maxCacheSize/3}.bind(this)).each(function(a){this.cache.unset(a.key);this.keys.unset(a.key)}.bind(this)))}});Lvs.IncrementalSearch.CacheData.getInstance=function(a){null==this.instance&&(this.instance=new this(a));return this.instance};
Lvs.IncrementalSearch.Configure={USE_HIDDEN_ITEM:!1,ADDRESS_MODE:!1,REQUEST_URL:"/api/suggest_station",FULL_MATCH_URL:"/api/full_match_station",REQUEST_KEY:"query",TEXT_FIELD_ID:"incTextInput",HIDDEN_FIELD_ID:"incHiddenInput",SELECT_BOX_WIDTH:100,SELECT_BOX_LEFT_OFFSET:0,FOCUS_CALLBACK:function(){},Z_INDEX:2E3,PREPROCESS_CALLBACK:function(a){}};
Lvs.IncrementalSearch.HiddenInput=Class.create({elem:null,initialize:function(a){this.elem=a},setValue:function(a){this.elem.value=a},getValue:function(){return this.elem.value},clear:function(){this.setValue("")}});
Lvs.IncrementalSearch.Preprocessor=Class.create({input:null,hidden:null,config:null,initialize:function(a,b,c){this.input=a;this.hidden=b;this.config=c},getText:function(){return this.input.getText()},setText:function(a){this.input.setText(a)},getId:function(){return this.hidden.getValue()},setId:function(a){this.hidden.setValue(a)},checkAndUpdate:function(a){if(a){var b=this.config.REQUEST_KEY,c=this.input.getText();new Ajax.Request(this.config.FULL_MATCH_URL,{method:"get",asynchronous:!1,parameters:b+
"="+c,onSuccess:a.curry(this)})}}});
Lvs.IncrementalSearch.SelectBox=Class.create({input:null,config:null,elem:null,list:null,options:null,selectedIndex:null,template:'<div class="incSelectList" style="width:#{width}px;"></div>',initialize:function(a,b){this.input=a;this.config=b;this.elem=this.createElement();this.list=this.elem.firstDescendant();this.options=[]},update:function(a){0==a.size()?this.hide():this.show(a)},hide:function(){this.clear();this.elem.hide()},isShow:function(){return 0<this.options.size()},getInput:function(){return this.input},
moveDown:function(){null==this.selectedIndex?this.selectedIndex=0:this.selectedIndex<this.options.size()-1?this.selectedIndex++:this.selectedIndex=null;this.updateSelectedOption()},moveUp:function(){null==this.selectedIndex?this.selectedIndex=this.options.size()-1:0<this.selectedIndex?this.selectedIndex--:this.selectedIndex=null;this.updateSelectedOption()},selectByOption:function(a){this.options.each(function(b,c){a==b?(b.selected(),this.selectedIndex=c):b.unselected()}.bind(this))},createOption:function(a){return new Lvs.IncrementalSearch.SelectOption(this,
a.id,a.name)},setPosition:function(){this.elem.setStyle(this.input.getStyleUnderLeftPosition())},show:function(a){this.clear();this.addOptions(a);this.setPosition();this.elem.show();this.config.Z_INDEX&&(this.elem.style.zIndex=this.config.Z_INDEX)},addOptions:function(a){this.options=$A(a).map(function(a){return this.createOption(a)}.bind(this))},clear:function(){this.options.each(function(a){a.remove()});this.options.clear();this.selectedIndex=null},createElement:function(){var a=new Element("div",
{className:"incSelectBox",style:"position: absolute;"});a.update((new Template(this.template)).evaluate({width:this.config.SELECT_BOX_WIDTH}));return $(a)},appendChild:function(a){this.list.appendChild(a)},removeChild:function(a){this.list.removeChild(a)},updateSelectedOption:function(){this.options.each(function(a){a.unselected()});if(null!=this.selectedIndex){var a=this.options[this.selectedIndex];a&&(a.selected(),this.input.setValue(a.getValue()))}}});
Lvs.IncrementalSearch.SelectBoxWithHiddenInput=Class.create(Lvs.IncrementalSearch.SelectBox,{initialize:function($super,b,c){$super(b,c);document.body.appendChild(this.elem)},createOption:function(a){return new Lvs.IncrementalSearch.SelectOptionWithHiddenInput(this,a.name,a.id)}});Lvs.IncrementalSearch.AddressSelectBox=Class.create(Lvs.IncrementalSearch.SelectBox,{createOption:function(a){return new Lvs.IncrementalSearch.AddressSelectOption(this,a)},setPosition:function(){},createElement:function(){return $("suggestBox")}});
void 0==Lvs&&(Lvs={});void 0==Lvs.Util&&(Lvs.Util={});Lvs.Util.Browser={isIE6:function(){return!this.isNotIE6()},isNotIE6:function(){return!Prototype.Browser.IE||Prototype.Browser.IE&&"undefined"!=typeof document.documentElement.style.maxHeight}};
Lvs.IncrementalSearch.SelectOption=Class.create({select:null,name:null,elem:null,template:"#{text}",initialize:function(a,b){this.select=a;this.name=b;this.elem=this.createElement();this.select.appendChild(this.elem);this.setEventListener()},getValue:function(){return{text:this.name}},selected:function(){Lvs.Util.Browser.isIE6()&&(this.elem.style.height="19px");this.elem.addClassName("selected")},unselected:function(){Lvs.Util.Browser.isIE6()&&(this.elem.style.height="19px");this.elem.removeClassName("selected")},
remove:function(){this.select.removeChild(this.elem)},createElement:function(){var a=new Element("div");a.update((new Template(this.template)).evaluate({text:this.name}));return $(a)},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this));this.elem.observe("mouseover",this.mouseover.bindAsEventListener(this))},click:function(a){this.select.getInput().setValue(this.getValue())},mouseover:function(){this.select.selectByOption(this)}});
Lvs.IncrementalSearch.SelectOptionWithHiddenInput=Class.create(Lvs.IncrementalSearch.SelectOption,{id:null,template:'#{text}<input type="hidden" value="#{id}" />',initialize:function($super,b,c,d){this.id=d;$super(b,c)},getValue:function(){return{text:this.name,id:this.id}}});
Lvs.IncrementalSearch.AddressSelectOption=Class.create(Lvs.IncrementalSearch.SelectOption,{template:'<li><a href="javascript:void(0);">#{text}</a></li>',selected:function(){this.elem.addClassName("selected")},unselected:function(){this.elem.removeClassName("selected")},createElement:function(){var a=this.select.getInput().getText(),b=new Element("ul");b.update((new Template(this.template)).evaluate({text:this.name.replace(a,"<b>"+a+"</b>")}));return $(b).down()}});
Lvs.IncrementalSearch.TextInput=Class.create({elem:null,select:null,cache:null,config:null,timerId:null,current:"",initialize:function(a,b,c){this.elem=a;this.cache=b;this.config=c;this.elem.setAttribute("autocomplete","off");this.setEventListener()},setSelect:function(a){this.select=a},setValue:function(a){this.setText(a.text)},getText:function(){return this.elem.value},setText:function(a){this.elem.value=a},getStyleUnderLeftPosition:function(){var a=this.elem.cumulativeOffset();return{top:a.top+
this.elem.getHeight()+"px",left:a.left+this.config.SELECT_BOX_LEFT_OFFSET+"px"}},reset:function(){},setEventListener:function(){Event.observe(this.elem,Prototype.Browser.Opera?"keypress":"keydown",this.keydown.bindAsEventListener(this));Event.observe(this.elem,"keyup",this.keyup.bindAsEventListener(this));Event.observe(this.elem,"blur",this.blur.bindAsEventListener(this));Event.observe(this.elem,"focus",this.config.FOCUS_CALLBACK);Event.observe(document.body,"click",this.clearAutocomplete.bindAsEventListener(this))},
keydown:function(a){switch(a.keyCode){case Event.KEY_ESC:case Event.KEY_TAB:case Event.KEY_RETURN:this.clearAutocomplete();break;case Event.KEY_DOWN:this.select.isShow()||this.change();this.select.moveDown();break;case Event.KEY_UP:this.select.isShow()?this.select.moveUp():(this.change(),this.select.moveDown());break;case Event.KEY_BACKSPACE:break;default:Prototype.Browser.Gecko&&null==this.timerId&&(this.timerId=setInterval(this.change.bind(this),100))}},keyup:function(a){this.clearDelayFunction();
switch(a.keyCode){case Event.KEY_DOWN:break;case Event.KEY_UP:break;case Event.KEY_BACKSPACE:this.change();break;default:Prototype.Browser.Gecko||this.change()}""==this.elem.value&&this.select.hide()},blur:function(a){this.clearDelayFunction()},clearAutocomplete:function(){this.clearDelayFunction();this.select.hide()},clearDelayFunction:function(){null!=this.timerId&&(clearInterval(this.timerId),this.timerId=null)},change:function(){var a=this.elem.value,b=this.current;this.current=a;""===a?this.clearAutocomplete():
(b!=a&&this.reset(),this.update(a))},update:function(a){var b=this.cache.get(a);b?this.select.update(b):this.searchAndUpdate(a)},searchAndUpdate:function(a){new Ajax.Request(this.config.REQUEST_URL,{method:"get",asynchronous:!0,parameters:this.config.REQUEST_KEY+"="+a,onSuccess:this.onSuccess.curry(a).bind(this)})},onSuccess:function(a,b){var c=b.responseJSON;this.cache.set(a,c);this.select.update(c)}});
Lvs.IncrementalSearch.TextInputWithHiddenInput=Class.create(Lvs.IncrementalSearch.TextInput,{hidden:null,initialize:function($super,b,c,d,e){$super(b,c,d);this.hidden=e},setValue:function(a){this.setText(a.text);this.setId(a.id)},reset:function(){this.setId("")},setId:function(a){this.hidden.setValue(a)}});
Lvs.Search.Form.ModalWindow.Builder=Class.create({elem:null,form:null,modal:null,initialize:function(a,b){this.elem=a;this.form=b;this.modal=this.createModalWindow();this.setup()},getModalWindow:function(){return this.modal},buildViewer:function(){this.modal.setViewer(this.createViewer())},buildClearButtons:function(){this.modal.setClearButtons(this.createClearButtons())},buildCloseButtons:function(){this.modal.setCloseButtons(this.createCloseButtons())},buildSubmitButtons:function(){this.modal.setSubmitButtons(this.createSubmitButtons())},
buildTabs:function(){this.modal.tabMgr.clear();this.modal.chkMgr.clear();this.getTabElements().each(function(a){a.hasClassName("notTab")||(a=new Lvs.Search.Form.ModalWindow.Tab.Item(a,this.modal),a.getMediators().each(function(a){a.setViewer(this.modal.viewer);this.modal.chkMgr.add(a)}.bind(this)),this.modal.tabMgr.add(a))}.bind(this))},setErrorMessage:function(a){},createViewer:function(){var a=this.getViewerElement();return new Lvs.Search.Form.ModalWindow.CheckedSummaryViewer(a,this.modal)},createClearButtons:function(){return this.getClearButtonElements().map(function(a){return new Lvs.Search.Form.ModalWindow.ClearButton(a,
this.modal)}.bind(this))},createCloseButtons:function(){return this.getCloseButtonElements().map(function(a){return new Lvs.Search.Form.ModalWindow.CloseButton(a,this.modal)}.bind(this))},createSubmitButtons:function(){return this.getSubmitButtonElements().map(function(a){return this.createSubmitButton(a,this.modal)}.bind(this))},createSubmitButton:function(a){throw Error("Not Implementation Error");},createModalWindow:function(){throw Error("Not Implementation Error");},open:function(){new Ajax.Request(this.modal.getUrl(),
this.getAjaxOptions())},close:function(){-1!=navigator.userAgent.indexOf("MSIE 6.0")&&$j(".nonDisplayIfModalMode").show();this.setHTML("")},afterSetHTML:function(){},setup:function(){this.elem.lightbox_me(this.getLightboxMeOptions())},getViewerElement:function(){return $$(".selectedArea li.area")[0]},getCloseButtonElements:function(){return $$(".closeBtn a")},getClearButtonElements:function(){return $$(".clearBtn a")},getSubmitButtonElements:function(){return $$(".submitBtn a")},getTabElements:function(){return $$(Lvs.Search.Form.Configure.TAB_CSS_EXPR)},
getLightboxMeOptions:function(){return{centered:!1,modalCSS:this.getModalCSS(),onLoad:this.open.bindAsEventListener(this),onClose:this.close.bindAsEventListener(this)}},getAjaxOptions:function(){return{method:"get",parameters:this.getParameters(),onSuccess:this.onSuccess.bind(this),asynchronous:!1}},getModalCSS:function(){return{position:"absolute",top:this.getTopPosition()+"px"}},getTopPosition:function(){return document.viewport.getScrollOffsets().top+40},getParameters:function(){return this.form.serialize()},
onSuccess:function(a){-1!=navigator.userAgent.indexOf("MSIE 6.0")&&$j(".nonDisplayIfModalMode").hide();this.setHTML(a.responseText);this.afterSetHTML();(new Lvs.Search.Form.ModalWindow.Director(this)).buildModalWindow()},setHTML:function(a){$(this.modal.getId()).innerHTML=a}});
Lvs.Search.Form.ModalWindow.AreaBuilder=Class.create(Lvs.Search.Form.ModalWindow.Builder,{createSubmitButton:function(a){return new Lvs.Search.Form.ModalWindow.AreaSubmitButton(a,this.modal)},createModalWindow:function(){return new Lvs.Search.Form.ModalWindow.Area(this.elem,this.form)}});
Lvs.Search.Form.ModalWindow.LineBuilder=Class.create(Lvs.Search.Form.ModalWindow.Builder,{createSubmitButton:function(a){return new Lvs.Search.Form.ModalWindow.LineSubmitButton(a,this.modal)},createModalWindow:function(){return new Lvs.Search.Form.ModalWindow.Line(this.elem,this.form)}});
Lvs.Search.Form.ModalWindow.TimeBuilder=Class.create(Lvs.Search.Form.ModalWindow.Builder,{highlightling:!1,cache:{},close:function($super){$$(".incSelectList").each(function(b){b.remove()});$super()},setErrorMessage:function(a){var b=new Element("span");b.innerHTML=a;this.errorMsgBox.update(b);this.highlight()},afterSetHTML:function(){Lvs.IncrementalSearch.init({USE_HIDDEN_ITEM:!0,SELECT_BOX_WIDTH:320,Z_INDEX:2E3,FOCUS_CALLBACK:function(){this.errorMsgBox.update("")}.bindAsEventListener(this),SELECT_BOX_LEFT_OFFSET:-1!=
navigator.userAgent.indexOf("MSIE 6.0")?-19:0,PREPROCESS_CALLBACK:this.preprocessor.bind(this)})},onSuccess:function($super,b){$super(b);this.errorMsgBox=$$("#timeSelectBox .error")[0];var c=new Lvs.Search.Form.ModalWindow.TimeOption.Base(this),d=$("searchPopupTimeSelectInner");d&&(c.setElement(d),new Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Builder(this.modal));$$(".incSelectBox").each(function(b){b.style.zIndex=1002});var e=$$(".openTimeSelectOption").map(function(b){return new Lvs.Search.Form.ModalWindow.TimeOption.Button(b,
c)});d&&e.each(function(b){b.toggle()});$$(".timeSelectOptionItem").each(function(b){new Form.Element.Observer(b,.3,function(){c.visible()&&e.each(function(b){b.click()})})})},createSubmitButton:function(a){return new Lvs.Search.Form.ModalWindow.TimeSubmitButton(a,this.modal)},createModalWindow:function(){return new Lvs.Search.Form.ModalWindow.Time(this.elem,this.form)},preprocessor:function(a){var b=this;$$(".preCheckable").each(function(c){c.observe("click",function(c){c=a.getText();if(!c)return b.setErrorMessage("\u99c5\u540d\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044");
this.cache[c]?this.checkAndUpdateForPreprocessor(a,this.cache[c]):a.checkAndUpdate(this.checkAndUpdateForPreprocessor.bind(this))}.bindAsEventListener(this))}.bind(this))},checkAndUpdateForPreprocessor:function(a,b){var c=a.getText(),d=b.responseJSON;this.cache[c]=b;1==d.size()?a.setId(d[0].id):d.any(function(a){return a.name==c})||this.setErrorMessage(0==d.size()?"\u5165\u529b\u3057\u305f\u99c5\u540d\u304c\u5b58\u5728\u3057\u307e\u305b\u3093":"\u5165\u529b\u3057\u305f\u99c5\u540d\u304c\u8907\u6570\u5b58\u5728\u3057\u307e\u3059")},
highlight:function(){this.highlighting||(this.highlighting=!0,$("incTextInput").highlight({startcolor:"#FFDDDD",afterFinish:function(){this.highlighting=!1}.bindAsEventListener(this)}))}});Lvs.Search.Form.ModalWindow.Checkbox={};
Lvs.Search.Form.ModalWindow.Checkbox.Base=Class.create({elem:null,name:null,mediator:null,initialize:function(a,b,c){this.elem=a;this.name=b;this.mediator=c;this.setEventListener()},click:function(){throw Error("Not Implementation Error");},init:function(){},check:function(a){this.elem.checked=a},checked:function(){return this.elem.checked},getName:function(){return this.name},setName:function(a){this.name=a},getValue:function(){return this.elem.value},setValue:function(a){this.elem.value=a},createInputDecoratedWithLabel:function(){return this.createLabel(this.createInput())},
setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))},createInput:function(){var a=new Element("input",this.getInputAttributes());a.name=this.getAttributeName();return a},getInputAttributes:function(){return{id:this.getAttributeName().replace("[]","")+this.getValue(),type:"checkbox",value:this.getValue(),checked:!0}},getAttributeName:function(){return this.elem.name.split("_")[1]+"[]"},createLabel:function(a){var b=new Element("label");b.appendChild(a);b.htmlFor=
a.id;b.appendChild(document.createTextNode(this.getName()));return b}});Lvs.Search.Form.ModalWindow.Checkbox.Parent=Class.create(Lvs.Search.Form.ModalWindow.Checkbox.Base,{click:function(){this.mediator.updateAllChildren(this.elem.checked);this.mediator.getChildren().each(function(a){this.mediator.setAllCheck(a.getValue(),a.checked())}.bind(this));this.mediator.updateAllParents();this.mediator.updateViewer()},init:function(){this.check(!1);this.setName("");this.setValue("")}});
Lvs.Search.Form.ModalWindow.Checkbox.Child=Class.create(Lvs.Search.Form.ModalWindow.Checkbox.Base,{click:function(){this.mediator.setAllCheck(this.getValue(),this.checked());this.mediator.updateAllParents();this.mediator.updateViewer()},init:function(){}});
Lvs.Search.Form.ModalWindow.Checkbox.Manager=Class.create({mediators:null,initialize:function(){this.mediators=[]},add:function(a){this.mediators.push(a)},clear:function(){this.initialize()},clearCheckboxes:function(){this.mediators.each(function(a){a.checkAll(!1)})},getText:function(){return this.getUniqueFilteredMediators().map(function(a){return a.getText()}).join("&nbsp;")},getInputsDecoratedWithLabel:function(){return this.getCheckedElements().map(function(a){return a.createInputDecoratedWithLabel()})},
getParentsIfAnyCheckedChildren:function(){return this.getFilteredMediator().map(function(a){return a.getParent()})},getUniqueChildrenCheckedValues:function(){return this.mediators.inject([],function(a,b){return a.concat(b.getChildrenCheckedValues())}).uniq()},countIfChecked:function(){return this.mediators.inject(0,function(a,b){return a+b.countIfChecked()})},setAllCheck:function(a,b){this.mediators.each(function(c){c.setCheck(a,b)})},updateAllParents:function(){this.mediators.each(function(a){a.visible()&&
a.updateParent(a.isCheckedAllChildren())})},getIgnoreChildren:function(){return this.getChildrenInCheckedParent(this.getUniqueFilteredMediators())},getChildrenInCheckedParent:function(a){return a.inject($H(),function(a,c){return a.merge(c.getIdToTextMapInCheckedParent())})},getUniqueFilteredMediators:function(){var a={};this.getFilteredMediator().each(function(b){a[b.getParent().getValue()]=b});return $H(a).values()},getFilteredMediator:function(){return this.mediators.filter(function(a){return a.isCheckedAnyChildren()})},
getCheckedElements:function(){return this.mediators.inject([],function(a,b){return a.concat(b.getCheckedElements())})}});Lvs.Search.Form.ModalWindow.Checkbox.TimeManager=Class.create(Lvs.Search.Form.ModalWindow.Checkbox.Manager,{getText:function(){var a=this.getUniqueFilteredMediators(),b=this.getChildrenInCheckedParent(a);return a.inject($H(),function(a,b){return a.merge(b.getIdToTextMap())}).filter(function(a){return!b.get(a.key)}).map(function(a){return"<strong>"+a.value+"</strong>"}).join("&nbsp;")}});
Lvs.Search.Form.ModalWindow.Checkbox.Mediator=Class.create({box:null,name:null,mgr:null,initialize:function(a,b,c,d){this.box=$(b.parentNode.parentNode);this.name=a;this.mgr=d;this.setupCheckboxes($(b),$(c))},configure:function(a,b){this.box.getElementsBySelector("ul.arealist").first().innerHTML=a;var c=this.box.getElementsBySelector(".areaAll label").first(),d=this.box.getElementsBySelector(".arealist label"),e=b.getChildrenCheckboxValues(),f=$(this.box.parentNode).getElementsBySelector(".selectLine").first();
this.name=f.options[f.selectedIndex].text;c.down().value=$F(f);this.setupCheckboxes(c,d);d.each(function(a){a=a.down();a.checked=e.include(a.value)});this.isCheckedAllChildren()&&this.checkParent(!0);b.viewer.update();this.show()},getParent:function(){return this.parent},getChildren:function(){return this.children},visible:function(){return 0!=this.children.size()},setupCheckboxes:function(a,b){this.hashMap={};this.parent=this.createParent($(a.firstChild));this.children=this.createChildren($(b))},
setAllCheck:function(a,b){this.mgr.setAllCheck(a,b)},setCheck:function(a,b){this.hashMap[a]&&this.hashMap[a].check(b)},isCheckedAllChildren:function(){return this.children.all(function(a){return a.checked()})},isCheckedAnyChildren:function(){return this.children.any(function(a){return a.checked()})},updateAllChildren:function(a){this.checkAllChildren(a)},updateAllParents:function(){this.mgr.updateAllParents()},updateParent:function(a){this.checkParent(a)},setViewer:function(a){this.viewer=a},updateViewer:function(){this.viewer.update()},
checkAll:function(a){this.checkAllChildren(a);this.checkParent(a)},getText:function(){return(new Template("<strong>#{parent}</strong>(#{child})")).evaluate({parent:this.name,child:this.getChildrenText()})},countIfChecked:function(){return this.getCheckedElements().size()},show:function(a){void 0===a&&(a=function(){});$j(this.box).slideDown("normal",a)},hide:function(a){void 0===a&&(a=function(){});$j(this.box).slideUp("normal",a)},getCheckedElements:function(){return this.parent.checked()?[this.parent]:
this.getFilteredChildren()},getChildrenCheckedValues:function(){return this.getFilteredChildren().map(function(a){return a.getValue()})},getIdToTextMap:function(){var a=$H();this.parent.checked()?a.set("line"+this.parent.getValue(),this.parent.getName()):this.getFilteredChildren().each(function(b){a.set("station"+b.getValue(),b.getName())});return a},getIdToTextMapInCheckedParent:function(){var a=$H();return this.parent.checked()?this.children.inject(a,function(a,c){a.set("station"+c.getValue(),c.getName());
return a}):a},clear:function(){this.parent.init();this.children=[];this.updateViewer();this.box.getElementsBySelector("ul.arealist li").each(function(a){a.remove()})},checkAllChildren:function(a){this.children.each(function(b){b.check(a)})},checkParent:function(a){this.parent.check(a)},getChildrenText:function(){return this.isCheckedAllChildren()?"\u5168\u3066":this.getTruncatedNameList()},getTruncatedNameList:function(){return this.getNameList().truncate(30)},getNameList:function(){return this.getNames().join("\u3001")},
getNames:function(){return this.getFilteredChildren().map(function(a){return a.getName()})},getFilteredChildren:function(){return this.children.filter(function(a){return a.checked()})},createParent:function(a){return new Lvs.Search.Form.ModalWindow.Checkbox.Parent(a,this.name,this)},createChildren:function(a){return a.map(function(a){var c=$(a.firstChild);if(c.disabled)return!1;a=new Lvs.Search.Form.ModalWindow.Checkbox.Child(c,a.textContent||a.innerText,this);return this.hashMap[a.getValue()]=a}.bind(this)).filter(function(a){return a})}});
Lvs.Search.Form.ModalWindow.CheckedSummaryViewer=Class.create({elem:null,modal:null,initialize:function(a,b){this.elem=a;this.modal=b},update:function(){this.elem.innerHTML=this.modal.getCheckedSummaryText()}});Lvs.Search.Form.ModalWindow.ClearButton=Class.create({elem:null,modal:null,initialize:function(a,b){this.elem=a;this.modal=b;this.setEventListener()},click:function(){this.modal.clearAll()},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))}});
Lvs.Search.Form.ModalWindow.CloseButton=Class.create({elem:null,modal:null,initialize:function(a,b){this.elem=a;this.modal=b;this.setEventListener()},click:function(){this.modal.close()},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))}});
Lvs.Search.Form.ModalWindow.Director=Class.create({builder:null,initialize:function(a){this.builder=a},buildModalWindow:function(){this.builder.buildViewer();this.builder.buildClearButtons();this.builder.buildCloseButtons();this.builder.buildSubmitButtons();this.builder.buildTabs()}});
Lvs.Search.Form.ModalWindow.Factory=Class.create({id:Lvs.Search.Form.Configure.MODAL_WINDOW_ID,elem:null,form:null,initialize:function(a){this.elem=jQuery("#"+this.id);this.form=a},create:function(){return this.createBuilder().getModalWindow()},createBuilder:function(){throw Error("Not Implementation Error");}});Lvs.Search.Form.ModalWindow.AreaFactory=Class.create(Lvs.Search.Form.ModalWindow.Factory,{createBuilder:function(){return new Lvs.Search.Form.ModalWindow.AreaBuilder(this.elem,this.form)}});
Lvs.Search.Form.ModalWindow.LineFactory=Class.create(Lvs.Search.Form.ModalWindow.Factory,{createBuilder:function(){return new Lvs.Search.Form.ModalWindow.LineBuilder(this.elem,this.form)}});Lvs.Search.Form.ModalWindow.TimeFactory=Class.create(Lvs.Search.Form.ModalWindow.Factory,{createBuilder:function(){return new Lvs.Search.Form.ModalWindow.TimeBuilder(this.elem,this.form)}});
Lvs.Search.Form.ModalWindow.OpenButton=Class.create({elem:null,factory:null,initialize:function(a,b){this.elem=a;this.factory=b;this.setEventListener()},click:function(){this.modal=this.factory.create();return!1},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))}});Lvs.Search.Form.ModalWindow.Selector={};
Lvs.Search.Form.ModalWindow.Selector.Base=Class.create({elem:null,mediator:null,initialize:function(a,b){this.elem=a;this.mediator=b;this.setEventListener()},change:function(){throw Error("Not Implementation Error");},clear:function(){$A(this.elem.options).each(function(a){$(a).remove()});this.addOption("\u9078\u629e\u3057\u3066\u304f\u3060\u3055\u3044","")},addOptions:function(a){$A(a).each(function(a){this.addOption(a.name,a.id)}.bind(this))},addOption:function(a,b){var c=new Option(a,b);c.innerText=
a;this.elem.appendChild(c)},getValue:function(){return this.elem.value},setEventListener:function(){this.elem.observe("change",this.change.bindAsEventListener(this))}});Lvs.Search.Form.ModalWindow.Selector.Company=Class.create(Lvs.Search.Form.ModalWindow.Selector.Base,{change:function(){this.mediator.updateLine()}});Lvs.Search.Form.ModalWindow.Selector.Line=Class.create(Lvs.Search.Form.ModalWindow.Selector.Base,{change:function(){this.mediator.updateCheckboxes()}});
Lvs.Search.Form.ModalWindow.Selector.Mediator=Class.create({company:null,line:null,modal:null,checkboxMediator:null,lineUpdater:null,stationUpdater:null,initialize:function(a,b,c,d){this.company=new Lvs.Search.Form.ModalWindow.Selector.Company(a,this);this.line=new Lvs.Search.Form.ModalWindow.Selector.Line(b,this);this.modal=c;this.checkboxMediator=d;this.lineUpdater=new Lvs.Search.Form.ModalWindow.Updater.Line(this);this.stationUpdater=new Lvs.Search.Form.ModalWindow.Updater.Station(this)},updateLine:function(){this.checkboxMediator.hide(function(){this.checkboxMediator.clear();
this.lineUpdater.update(this.getParameters())}.bind(this))},updateCheckboxes:function(){this.checkboxMediator.hide(function(){this.checkboxMediator.clear();var a=this.line.getValue();a&&this.stationUpdater.update({line_id:a})}.bind(this))},getParameters:function(){return{railroad_company_id:this.company.getValue(),pref_id:this.modal.getCurrentPrefId()}}});
Lvs.Search.Form.ModalWindow.SubmitButton=Class.create({elem:null,modal:null,hiddenSelectors:".jobAreaTTL #jobCheckTable .jobStaSelect .stationCheckList #stationCheckTable .timeAreaTTL #timeCheckTable".split(" "),removeSelectors:"li.checkedStation;#jobCheckTable .mainTown li.checkedArea;.localTab;.subTown;.selectLineHidden;.timeResultHiddenItems;.beforeSearch;#search_panel_guide_link_list".split(";"),initialize:function(a,b){this.elem=a;this.modal=b;this.setEventListener()},click:function(){throw Error("Not Implementaion Error");
},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))},removeOldElements:function(){this.removeSelectors.each(function(a){$$(a).each(function(a){a.remove()})})},allClose:function(a){$("topSection").appendChild(a);var b=$("topSection");b.blindUp({duration:.4,afterFinish:function(){$$(".jobStaSelect2").each(function(a){a.hide()});$("jobOrStaionCheckTable").show();$$(".jobStaSelect").each(function(a){a.show()});b.blindDown({duration:.5})}})},open:function(a){this.appendMatchNumber(a);
this.hide(this.show)},appendMatchNumber:function(a){},show:function(){},hide:function(a){$$($$(".jobStaSelect")[0].visible()?".jobStaSelect":".jobStaSelect2").each(function(b){b.blindUp({duration:.4,afterFinish:function(){this.hiddenSelectors.each(function(a){$$(a).each(function(a){a.hide()})});a()}.bind(this)})}.bind(this))}});
Lvs.Search.Form.ModalWindow.AreaSubmitButton=Class.create(Lvs.Search.Form.ModalWindow.SubmitButton,{click:function(){var a=this.modal.getInputsDecoratedWithLabel(),b=$$("#jobCheckTable .mainTown ul")[0],c=$("selectAreaAgain"),d=$("matchNumber");this.removeOldElements();this.updateCheckboxes(a,b);b.appendChild(c);this.reflesh(a,d)},show:function(){[".areaCheckList"].each(function(a){$$(a).each(function(a){a.show()})});$$(".jobStaSelect2").each(function(a){a.blindDown({duration:.4})})},updateCheckboxes:function(a,
b){a.each(function(a){var d=new Element("li");d.className="checkedArea";d.appendChild(a);b.appendChild(d);a.down().checked=!0})},reflesh:function(a,b){b.remove();0==a.size()?this.allClose(b):this.open(b);this.modal.close()},appendMatchNumber:function(a){setTimeout(function(){$("jobCheckTable").down().appendChild(a)},600)}});
Lvs.Search.Form.ModalWindow.LineSubmitButton=Class.create(Lvs.Search.Form.ModalWindow.SubmitButton,{click:function(){var a=this.modal.getUniqueInputsDecoratedWithLabel(),b=$$("#stationCheckTable ul")[0],c=$("selectLineAgain"),d=$("matchNumber");this.removeOldElements();this.updateCheckboxes(a,b);this.updateLineHidden();b.appendChild(c);this.reflesh(a,d)},show:function(){[".stationCheckList"].each(function(a){$$(a).each(function(a){a.show()})});$$(".jobStaSelect2").each(function(a){a.blindDown({duration:.4})})},
updateCheckboxes:function(a,b){a.each(function(a){var d=document.createElement("li");"station[]"==a.down().name&&(a.innerHTML+="\u99c5");d.className="checkedStation";d.appendChild(a);b.appendChild(d);a.down().checked=!0})},updateLineHidden:function(){var a=$("searchForm");$H(this.modal.getAllParentByEachCheckedChildren()).each(function(b){var c=b.key;b.value.each(function(b){var e=new Element("input",{type:"hidden"});e.name="select_line["+c+"][]";e.className="selectLineHidden";e.value=b.getValue();
a.appendChild(e)})})},reflesh:function(a,b){b.remove();0==a.size()?this.allClose(b):this.open(b);this.modal.close()},appendMatchNumber:function(a){setTimeout(function(){$("stationCheckTable").down().appendChild(a)},600)}});
Lvs.Search.Form.ModalWindow.TimeSubmitButton=Class.create(Lvs.Search.Form.ModalWindow.SubmitButton,{click:function(){if($("incHiddenInput").value){var a=this.modal.getIgnoredUniqueInputsDecoratedWithLabel(),b=$$("#timeResultList ul")[0],c=$("selectTimeAgain"),d=$("matchNumber");this.removeOldElements();this.updateStationInfo();this.updateCheckboxes(a,b);b.appendChild(c);this.reflesh(a,d)}},show:function(){[".timeAreaTTL","#timeCheckTable"].each(function(a){$$(a).each(function(a){a.show()})});$$(".jobStaSelect2").each(function(a){a.blindDown({duration:.4})})},
updateCheckboxes:function(a,b){a.each(function(a){var d=document.createElement("li");"station[]"==a.down().name&&(a.innerHTML+="\u99c5");d.className="checkedStation";d.appendChild(a);b.appendChild(d);a.down().checked=!0})},updateStationInfo:function(){var a=$("incHiddenInput").value,b=$("incTextInput").value,c=$("timeSelectMinutes").value,d=$("timeSelectTimes").value,e=$("searchForm");$("timeResultStationName").innerHTML=b.escapeHTML()+"\u99c5";$("timeResultMinutes").innerHTML=c.escapeHTML()+"\u5206";
var f=$("timeResultTimes");f.innerHTML=""===d?"":0===d?"\uff08\u4e57\u308a\u63db\u3048\u306a\u3057\uff09":"\uff08\u4e57\u308a\u63db\u3048"+d.escapeHTML()+"\u56de\uff09";f.show();$H({id:a,name:b,time:c,n:d}).each(function(a){var b=new Element("input");b.id="timeResultHidden"+a.key.capitalize();b.type="hidden";b.name="nmin["+a.key+"]";b.className="timeResultHiddenItems";b.value=a.value;e.appendChild(b)})},reflesh:function(a,b){b.remove();$("timeResultList")[a.size()?"show":"hide"]();this.open(b);this.modal.close()},
appendMatchNumber:function(a){setTimeout(function(){$("timeCheckTable").down().down().insert({after:a})},600)}});Lvs.Search.Form.ModalWindow.Tab={};
Lvs.Search.Form.ModalWindow.Tab.Contents=Class.create({elem:null,tab:null,modal:null,mediators:null,initialize:function(a,b){this.elem=a;this.tab=b;this.modal=b.getModalWindow();this.mediators=this.createMediators()},change:function(){this.elem.toggle()},show:function(){this.elem.show()},hide:function(){this.elem.hide()},getMediators:function(){return this.mediators},createMediators:function(){throw Error("Not Implementation Error");}});
Lvs.Search.Form.ModalWindow.Tab.AreaContents=Class.create(Lvs.Search.Form.ModalWindow.Tab.Contents,{createMediators:function(){return this.elem.getElementsBySelector(".areaAll").map(function(a){var b=a.getElementsBySelector("label").first();a=a.next().getElementsBySelector("label");return new Lvs.Search.Form.ModalWindow.Checkbox.Mediator(this.tab.getName(),b,a,this.modal.getCheckboxManager())}.bind(this))}});
Lvs.Search.Form.ModalWindow.Tab.LineContents=Class.create(Lvs.Search.Form.ModalWindow.Tab.Contents,{createMediators:function(){return this.elem.getElementsBySelector(".selectStation").map(function(a){var b=a.getElementsBySelector(".selectLine").first(),c=this.createCheckboxMediator(a,b);this.createSelectorMediator(a,b,c);return c}.bind(this))},createCheckboxMediator:function(a,b){var c=a.getElementsBySelector(".areaAll label").first(),d=a.getElementsBySelector(".arealist label");return new Lvs.Search.Form.ModalWindow.Checkbox.Mediator(b.options[b.selectedIndex].text,
c,d,this.modal.getCheckboxManager())},createSelectorMediator:function(a,b,c){a=a.getElementsBySelector(".selectCompany").first();return new Lvs.Search.Form.ModalWindow.Selector.Mediator(a,b,this.tab.modal,c)}});
Lvs.Search.Form.ModalWindow.Tab.TimeContents=Class.create(Lvs.Search.Form.ModalWindow.Tab.Contents,{createMediators:function(){var a=this.elem.getElementsBySelector(".areaAll label").first(),b=this.elem.getElementsBySelector(".arealist label");return[new Lvs.Search.Form.ModalWindow.Checkbox.Mediator(this.tab.getName(),a,b,this.modal.getCheckboxManager())]}});
Lvs.Search.Form.ModalWindow.Tab.Item=Class.create({elem:null,modal:null,tabMgr:null,contents:null,initialize:function(a,b){this.elem=a;this.modal=b;this.tabMgr=b.tabMgr;this.contents=this.createTabContents();this.setEventListener()},click:function(){this.tabMgr.init();this.elem.toggleClassName(this.getSelectedClassName());this.contents.change()},init:function(){this.elem.removeClassName(this.getSelectedClassName());this.contents.hide()},getMediators:function(){return this.contents.getMediators()},
getPrefId:function(){return parseInt(this.getContentsId().match(/[1-9]\d*/)[0])},isSelected:function(){return this.elem.hasClassName(this.getSelectedClassName())},getModalWindow:function(){return this.modal},getParentsIfAnyCheckedChildren:function(){return this.getFilteredMediator().map(function(a){return a.getParent()})},show:function(){this.elem.show()},hide:function(){this.elem.hide()},createTabContents:function(){return new (this.modal.getTabContentsClass())($(this.getContentsId()),this)},setEventListener:function(){this.elem.observe("click",
this.click.bindAsEventListener(this))},getName:function(){return this.elem.textContent||this.elem.innerText},getContentsId:function(){return this.elem.getElementsBySelector("a")[0].href.split("#")[1]},getSelectedClassName:function(){return Lvs.Search.Form.Configure.TAB_SELECTED_CLASS_NAME},getFilteredMediator:function(){return this.getMediators().filter(function(a){return a.isCheckedAnyChildren()})}});
Lvs.Search.Form.ModalWindow.Tab.Manager=Class.create({tabs:null,initialize:function(){this.tabs=[]},add:function(a){this.tabs.push(a)},get:function(a){return this.tabs.find(function(b){return b.getContentsId()==a})},clear:function(){this.initialize()},init:function(){this.tabs.each(function(a){a.init()})},getPrefId:function(){return this.getCurrent().getPrefId()},getAllParentByEachCheckedChildren:function(){var a={};this.tabs.each(function(b){a[b.getPrefId()]=b.getParentsIfAnyCheckedChildren()});
return a},getCurrent:function(){return this.tabs.detect(function(a){return a.isSelected()})}});Lvs.Search.Form.ModalWindow.TimeOption={};
Lvs.Search.Form.ModalWindow.TimeOption.Base=Class.create({modal:null,updater:null,img:null,initialize:function(a){this.modal=a.modal;this.updater=new Lvs.Search.Form.ModalWindow.TimeOption.Updater(this,a);this.img=$$("#timeSelectOptionForm .loading")[0]},getElement:function(){return this.elem},setElement:function(a){this.elem=a},update:function(a){this.updater.update(a)},visible:function(){return this.elem&&this.elem.visible()},toggle:function(a){this.img.show();this["blind"+(this.visible()?"Up":
"Down")](a)},blindDown:function(a){var b;b=a.afterFinishForButton?function(b){this.blindDownAfterFinish(b);a.afterFinishForButton(b)}.bind(this):this.blindDownAfterFinish.bind(this);this.update(function(c){void 0==c&&(c=!0);c?(this.disableOptionItems(),this.elem.blindDown(Object.extend({duration:.6,afterFinish:b},a))):b(c)}.bind(this))},blindUp:function(a){if(void 0!=this.elem&&this.elem.visible()){var b;b=a.afterFinishForButton?function(b){this.blindUpAfterFinish(b);a.afterFinishForButton(b)}.bind(this):
this.blindUpAfterFinish.bind(this);this.elem.blindUp(Object.extend({duration:.6,afterFinish:b.curry(!0)},a))}},blindDownAfterFinish:function(a){this.img.hide();a&&this.enableOptionItems()},blindUpAfterFinish:function(a){this.img.hide();this.modal.tabMgr.clear();this.modal.chkMgr.clear();this.elem=null},enableOptionItems:function(){this.applyOptionItems(function(a){a.disabled=!1})},disableOptionItems:function(){this.applyOptionItems(function(a){a.disabled=!0})},applyOptionItems:function(a){$$(".timeSelectOptionItem").each(a)},
getDefaultOptions:function(){return{duration:.6}}});
Lvs.Search.Form.ModalWindow.TimeOption.Button=Class.create({elem:null,option:null,animating:!1,initialize:function(a,b){this.elem=a;this.option=b;this.setEventListener()},setEventListener:function(){this.elem.down().observe("click",this.click.bindAsEventListener(this))},click:function(){!this.option.visible()&&!$("incHiddenInput").value||this.animating||(this.animating=!0,this.option.toggle({afterFinishForButton:this.toggle.bind(this)}))},toggle:function(a){if(a){a=this.elem.down();if(!a)return;a.toggleClassName("close");
a.innerHTML=a.hasClassName("close")?"\u9078\u629e\u30a8\u30ea\u30a2\u3092\u9589\u3058\u308b":"\u7bc4\u56f2\u5185\u306e\u99c5\u3092\u7d5e\u3063\u3066\u691c\u7d22"}this.animating=!1}});Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu={};void 0==Lvs&&(Lvs={});void 0==Lvs.Util&&(Lvs.Util={});
Lvs.Util.Scrollable=Class.create({elem:null,frame:null,handle:null,track:null,ratio:null,slider:null,wheelFunction:null,initialize:function(a,b,c){this.elem=a;this.frame=$(this.elem.parentNode.parentNode);this.handle=b;this.track=c;this.ratio=this.elem.scrollHeight/this.track.scrollHeight;this.setup();this.slider=this.createSlider();this.wheelFunction=this.wheel.bindAsEventListener(this);this.setEventListeners()},setup:function(){if(this.elem.scrollHeight>this.track.scrollHeight){var a=this.track.scrollHeight/
this.ratio;a>this.handle.getHeight()&&(this.handle.getElementsBySelector(".scrollHandleTop")[0].style.height=a+"px")}else this.track.hide()},setEventListeners:function(){this.track.visible()&&(window.addEventListener&&window.addEventListener("DOMMouseScroll",this.wheelFunction,!1),window.onmousewheel=document.onmousewheel=this.wheelFunction)},wheel:function(a){if(this.inRanct(a)){var b=0;a||(a=window.event);a.wheelDelta?b=a.wheelDelta/120:a.detail&&(b=-a.detail/3);b&&this.wheelEffect(b);a.preventDefault&&
a.preventDefault();a.returnValue=!1}},wheelEffect:function(a){this.slider.active=!0;this.slider.offsetX=1;this.slider.offsetY=1;this.slider.draw(this.createEvent(a));this.slider.active=!1},createEvent:function(a){var b=a*(1<this.ratio?5:5*this.ratio);a=this.handle.viewportOffset().left;b=this.handle.viewportOffset().top-b;if(document.createEvent){var c=document.createEvent("MouseEvents");c.initMouseEvent("mouseup",!0,!1,window,0,0,0,a,b,!1,!1,!1,!1,0,null)}else document.createEventObject&&(c=document.createEventObject(),
c.clientX=a,c.clientY=b);return Event.extend(c)},inRanct:function(a){a=Event.extend(a);if(!this.frame||!this.frame.visible())return!1;var b=document.viewport.getScrollOffsets(),c=a.pointerX()-b.left;a=a.pointerY()-b.top;b=this.frame.getClientRects()[0];return c>=b.left&&c<=b.right&&a>=b.top&&a<=b.bottom},onSlide:function(a){this.scrollVertical(a)},onChange:function(a){this.scrollVertical(a)},scrollVertical:function(a){this.elem.scrollTop=Math.round(a/this.slider.maximum*(this.elem.scrollHeight-this.elem.offsetHeight))},
createSlider:function(){return new Control.Slider(this.handle,this.track,this.getSliderOption())},getSliderOption:function(){return{axis:"vertical",onSlide:this.onSlide.bindAsEventListener(this),onChange:this.onSlide.bindAsEventListener(this)}}});
Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Builder=Class.create({menu:null,scrollable:null,btns:null,initialize:function(a){this.menu=this.createMenu(a);this.scrollable=this.createScrollable();this.btns=this.createButtons();this.menu.hide()},createMenu:function(a){return new Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Controller($$(".pulldownBox")[0],a)},createScrollable:function(){return new Lvs.Util.Scrollable($("scrollable"),$("pulldownScrollHandle"),$("scrollTrack"))},createButtons:function(){return $$(".otherTab").inject([],
function(a,b){var c=b.getElementsBySelector(".arrow")[0];return a.concat(b.getElementsBySelector("a.otherTabOpn").map(function(a){new Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Button(a,c,this.menu)}.bind(this)))}.bind(this))}});
Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Button=Class.create({elem:null,arrow:null,menu:null,initialize:function(a,b,c){this.elem=a;this.arrow=b;this.menu=c;this.setEventListener()},click:function(){this.menu.toggle();this.arrow.toggleClassName("active")},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))}});
Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Controller=Class.create({elem:null,modal:null,items:null,selectedItem:null,currentTab:null,onAnimating:!1,boundEventMouseDown:null,initialize:function(a,b){this.elem=a;this.modal=b;this.items=this.createItems();this.currentTab=this.selectedItem=null;this.onAnimating=!1;this.boundEventMouseDown=this.eventMouseDown.bindAsEventListener(this)},toggle:function(){this.visible()?this.blindUp():this.blindDown()},visible:function(){return this.elem.visible()},
hide:function(){this.elem.hide()},getSelectedItem:function(){return this.selectedItem},setSelectedItem:function(a){this.currentTab?this.currentTab.hide():$$(".notTab").each(function(a){a.hide()});this.currentTab=this.modal.tabMgr.get(a.getContentsId());this.currentTab.click();this.currentTab.show();this.selectedItem=a},blindDown:function(){this.blindEffect(this.elem.blindDown.bind(this.elem),this.setMouseDown)},blindUp:function(){$$(".otherTabOpn.arrow.active").each(function(a){a.removeClassName("active")});
this.blindEffect(this.elem.blindUp.bind(this.elem),this.unsetMouseDown)},blindEffect:function(a,b){this.onAnimating||(this.onAnimating=!0,a(this.getBlindOption(b)))},getBlindOption:function(a){return{duration:.3,afterFinish:function(){this.onAnimating=!1;a&&a.bind(this)()}.bind(this)}},setMouseDown:function(){Event.observe(document,"mousedown",this.boundEventMouseDown)},unsetMouseDown:function(){Event.stopObserving(document,"mousedown",this.boundEventMouseDown)},eventMouseDown:function(a){this.inRect(a)||
this.blindUp()},inRect:function(a){var b=document.viewport.getScrollOffsets(),c=a.pointerX()-b.left;a=a.pointerY()-b.top;b=this.elem.getClientRects()[0];return c>=b.left&&c<=b.right&&a>=b.top&&a<=b.bottom},createItems:function(){return this.elem.getElementsBySelector("a").map(function(a){return new Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Item(a,this)}.bind(this))}});
Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Item=Class.create({elem:null,menu:null,initialize:function(a,b){this.elem=a;this.menu=b;this.setEventListener()},getName:function(){return this.elem.textContent||this.elem.innerText},getContentsId:function(){return this.elem.href.split("#")[1]},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))},click:function(){this.menu.setSelectedItem(this);this.menu.blindUp()}});
Lvs.Search.Form.ModalWindow.TimeOption.Updater=Class.create({option:null,builder:null,modal:null,initialize:function(a,b){this.option=a;this.builder=b;this.modal=this.builder.modal},update:function(a){new Ajax.Request(this.getUrl(),this.getAjaxOptions(a))},getUrl:function(){return Lvs.Search.Form.Configure.TIME_OPTION_AJAX_URL},getAjaxOptions:function(a){return{method:"get",parameters:$("timeSelectOptionForm").serialize(),onSuccess:this.onSuccess.curry(a).bind(this)}},onSuccess:function(a,b){var c=
b.responseText;if(!c)return this.builder.setErrorMessage("\u7bc4\u56f2\u5185\u306e\u99c5\u304c\u3042\u308a\u307e\u305b\u3093"),a(!1);c=(new Element("div")).update(c);$("searchPopupTimeSelect").update(c);this.option.setElement(c);new Lvs.Search.Form.ModalWindow.TimeOption.PullDownMenu.Builder(this.modal);c.hide();this.builder.buildViewer();this.builder.buildTabs();this.builder.buildClearButtons();a(!0)}});Lvs.Search.Form.ModalWindow.Updater={};
Lvs.Search.Form.ModalWindow.Updater.Line=Class.create({mediator:null,initialize:function(a){this.mediator=a},update:function(a){new Ajax.Request(this.getUrl(),this.getAjaxOptions(a))},getUrl:function(){return Lvs.Search.Form.Configure.LINE_GET_AJAX_URL},getAjaxOptions:function(a){return{method:"get",parameters:a,onSuccess:this.onSuccess.bind(this),asynchronous:!1}},onSuccess:function(a){this.mediator.line.clear();this.mediator.line.addOptions(a.responseJSON)}});
Lvs.Search.Form.ModalWindow.Updater.Station=Class.create({mediator:null,initialize:function(a){this.mediator=a},update:function(a){new Ajax.Request(this.getUrl(),this.getAjaxOptions(a))},getUrl:function(){return Lvs.Search.Form.Configure.STATION_GET_AJAX_URL},getAjaxOptions:function(a){return{method:"get",parameters:a,onSuccess:this.onSuccess.bind(this),asynchronous:!1}},onSuccess:function(a){this.mediator.checkboxMediator.configure(a.responseText,this.mediator.modal)}});
Lvs.Search.Form.MoreGuideLinksToggle=Class.create({toggleLinks:null,guideLinkList:null,visible:null,initialize:function(a,b){this.toggleLinks=a;this.guideLinkList=b;this.visible=!1;this.setEventListener()},setEventListener:function(){this.toggleLinks.each(function(a){a.observe("click",this.toggle.bindAsEventListener(this))}.bind(this))},toggle:function(){this.visible?this.close():this.open();this.visible=!this.visible},close:function(){this.guideLinkList.blindUp({duration:.3});this.toggleLinks[0].hide();
this.toggleLinks[1].show()},open:function(){this.guideLinkList.blindDown({duration:.3});this.toggleLinks[1].hide();this.toggleLinks[0].show()}});Lvs.Search.Form.MoreGuideLinksToggle.setup=function(a,b){a&&b&&new Lvs.Search.Form.MoreGuideLinksToggle(a,b)};
Lvs.Search.Form.MoreSearchOptionButton=Class.create({elem:null,option:null,initialize:function(a,b){this.elem=a;this.option=b;this.setEventListener()},click:function(){this.elem.hasClassName("optionOpenBtn")?this.open():this.close()},open:function(){this.elem.down().getStyle("bottom");$j(this.option).slideDown("fast",function(){this.elem.removeClassName("optionOpenBtn");this.elem.addClassName("optionCloseBtn")}.bind(this))},close:function(){this.elem.down().getStyle("bottom");$j(this.option).slideUp(function(){this.elem.removeClassName("optionCloseBtn");
this.elem.addClassName("optionOpenBtn")}.bind(this));$A(this.option.getElementsBySelector("input")).each(function(a){a.checked=!1});$A(this.option.getElementsBySelector("select")).each(function(a){a.selectedIndex=0})},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))}});Lvs.Search.Form.MoreSearchOptionButton.setup=function(a,b){a&&b&&new Lvs.Search.Form.MoreSearchOptionButton(a,b)};
Lvs.Search.Form.NewMemberButton=Class.create({elem:null,form:null,config:null,initialize:function(a,b,c){this.elem=a;this.form=b;this.config=c;this.setEventListener()},click:function(){new Ajax.Request(this.getUrl(),this.getAjaxOptions())},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))},getUrl:function(){return this.config.SET_CHOICE_URL},getAjaxOptions:function(){return{method:"post",parameters:this.form.serialize(),onSuccess:function(a){},asynchronous:!1}}});
Lvs.Search.Form.NewMemberButton.setup=function(a,b){a.each(function(a){new Lvs.Search.Form.NewMemberButton(a,b,Lvs.Search.Form.Configure)})};Lvs.Search.Form.Observer=Class.create({elem:null,updater:null,initialize:function(a,b){this.elem=a;this.updater=b;this.setEventListener()},update:function(a,b){this.updater.clear();this.updater.update()},setEventListener:function(){new Form.Observer(this.elem,.3,this.update.bind(this))}});
Lvs.Search.Form.StationCheckbox=Class.create({elem:null,initialize:function(a){this.elem=a;this.setEventListener()},change:function(){$$(".stationSliderCheckbox"+this.elem.value).each(function(a){a.checked=this.elem.checked}.bind(this))},setEventListener:function(){this.elem.observe("click",this.change.bindAsEventListener(this))}});Lvs.Search.Form.StationCheckbox.setup=function(a){a.each(function(a){new Lvs.Search.Form.StationCheckbox(a)})};
Lvs.Search.Form.StationCheckboxInLineTab=Class.create({elem:null,initialize:function(a){this.elem=a;this.setEventListener()},change:function(){this.exists()||$("selectLineAgain").insert({before:this.createListItem()});$("station_"+this.getId()).checked=this.elem.checked;$$(".stationSliderCheckbox"+this.getId()).each(function(a){a.checked=this.elem.checked}.bind(this))},setEventListener:function(){this.elem.observe("click",this.change.bindAsEventListener(this))},exists:function(){return!!$("station_"+
this.elem.value)},getId:function(){return this.elem.value},getName:function(){return this.elem.next().innerHTML},createListItem:function(){var a=new Element("li",{className:"checkedStation"});a.insert(this.createLabel());return a},createLabel:function(){var a=new Element("label",{htmlFor:"station_"+this.getId()});a.insert({top:this.createCheckbox(),bottom:this.getName()});return a},createCheckbox:function(){var a=new Element("input",{id:"station_"+this.getId(),type:"checkbox",checked:"checked",name:"station[]",
value:this.getId()});new Lvs.Search.Form.StationCheckbox(a);return a}});Lvs.Search.Form.StationCheckboxInLineTab.setup=function(a){a.each(function(a){new Lvs.Search.Form.StationCheckboxInLineTab(a)})};Lvs.Search.Form.TimeCheck=Class.create({elem:null,initialize:function(a){this.elem=a;this.setEventListener()},click:function(){this.elem.toggleClassName(this.getClassName())},setEventListener:function(){this.elem.observe("click",this.click.bindAsEventListener(this))},getClassName:function(){return Lvs.Search.Form.Configure.TIME_SELECTED_CLASS_NAME}});
Lvs.Search.Form.TimeCheck.setup=function(a){a.each(function(a){new Lvs.Search.Form.TimeCheck(a)})};
Lvs.Search.Form.Tooltip=Class.create({elem:null,initialize:function(a){this.elem=a;this.setEventListener()},onMouseOver:function(){tooltip.show(this.id,this.attributes.getNamedItem("assistance").nodeValue.replace(/\n/g,"<br />"));-1!=navigator.userAgent.indexOf("MSIE 6.0")&&"newarrivalHintBtn"==this.id&&$("featureSelect2").hide()},onMouseOut:function(){-1!=navigator.userAgent.indexOf("MSIE 6.0")&&"newarrivalHintBtn"==this.id&&$("featureSelect2").show();tooltip.hide()},setEventListener:function(){this.elem.observe("mouseover",
this.onMouseOver);this.elem.observe("mouseout",this.onMouseOut)}});Lvs.Search.Form.Tooltip.setup=function(a){a.each(function(a){new Lvs.Search.Form.Tooltip(a)})};